ARG BASE_IMAGE="ghcr.io/siddhantmodi/zephyr-ci:zsdk_v0.17.4"
FROM ${BASE_IMAGE}

USER root

RUN apt update && \
    apt -y install screen && \
    apt -y install openocd && \
    apt -y install udev && \
    usermod -aG dialout $USERNAME

# Install STM32 SVD files
RUN cd /opt && git clone https://github.com/modm-io/cmsis-svd-stm32
ENV SVD_DIR=/opt/cmsis-svd-stm32

# Install nrfutil device runner tool - do it as user to avoid permission issues
USER $USERNAME
WORKDIR /home/$USERNAME/workspace
