ARG BASE_IMAGE
FROM ${BASE_IMAGE:-ghcr.io/siddhantmodi/zephyr-ci:zsdk_v0.17.0-amd64}

ARG arch=amd64

USER root

RUN apt update && \
    apt -y install screen && \
    apt -y install openocd

# Create the dialout group and add the user to it
RUN usermod -aG dialout $USERNAME

# Install STM32 SVD files
RUN cd /opt && git clone https://github.com/modm-io/cmsis-svd-stm32
ENV SVD_DIR=/opt/cmsis-svd-stm32

# Install nrfutil device runner tool - do it as user to avoid permission issues
USER $USERNAME
WORKDIR /home/$USERNAME/workspace
